init
jabajke/autohouse pull request #1
Opened 2023-01-10 21:31 UTC by jabajke

2023-01-11 12:29 UTC, shprexen requested changes

2023-01-11 12:29 UTC, shprexen commented on Dockerfile
> +
add  COPY command for requirements.txt as a separate command. So when you'll add new dependencies in requirements.txt docker image will be rebuilt

2023-01-11 12:29 UTC, shprexen commented on autohouse/models.py
> +class Auto(models.Model):
Let's name that model as Car

2023-01-11 12:29 UTC, shprexen commented on autohouse/models.py
> +    is_active = models.BooleanField(default=True)
create abstract model with fields, such as is_active, created_at and updated_at and inherit from it

2023-01-11 23:06 UTC, jabajke commented on Dockerfile
> +
done

2023-01-11 23:06 UTC, jabajke commented on autohouse/models.py
> +class Auto(models.Model):
done

2023-01-11 23:06 UTC, jabajke commented on autohouse/models.py
> +    is_active = models.BooleanField(default=True)
done

2023-01-12 13:03 UTC, shprexen commented on autohouse/models.py
> +    characteristic = models.ForeignKey('Characteristic', on_delete=models.CASCADE)
in the future will it be convenient to add filters on endpoint using such field?
I think it's better to store characteristics in `Car`, i.e. VIN, model, manufacturer, horse power and etc.
But you can use `JSONField` in `Autohouse` model to represent preferred characteristics

2023-01-12 15:56 UTC, jabajke commented on autohouse/models.py
> +    characteristic = models.ForeignKey('Characteristic', on_delete=models.CASCADE)
done

2023-01-13 12:31 UTC, shprexen requested changes

2023-01-13 12:31 UTC, shprexen commented on autohouse/models.py
> +    transmission_type = models.CharField(max_length=50)
Let's use here django choices, create choices with all types of transmission

2023-01-15 02:18 UTC, jabajke commented on autohouse/models.py
> +    transmission_type = models.CharField(max_length=50)
done

2023-01-16 08:05 UTC, shprexen approved these changes

2023-01-16 10:33 UTC, merged