offer scheduler added
jabajke/autohouse pull request #16
Opened 2023-02-17 11:37 UTC by jabajke

2023-02-20 13:10 UTC, shprexen requested changes

2023-02-20 13:10 UTC, shprexen commented on customer/tasks.py
> +            min_default_price = suitable_autohouse_car.order_by('price')[0]
let's use .first() method instead [0] and then check if such car exists, if it is not - we should keep somewhere information, that offer hasn't completed

2023-02-20 13:10 UTC, shprexen commented on customer/tasks.py
> +                .order_by('price'))[0]
the same, use .first method

2023-02-20 23:08 UTC, jabajke commented on customer/tasks.py
> +                .order_by('price'))[0]
done

2023-02-20 23:08 UTC, jabajke commented on customer/tasks.py
> +            min_default_price = suitable_autohouse_car.order_by('price')[0]
done

2023-02-21 12:40 UTC, shprexen approved these changes

2023-02-21 12:58 UTC, merged