Statistics
jabajke/autohouse pull request #17
Opened 2023-02-22 11:18 UTC by jabajke

2023-02-22 16:51 UTC, shprexen requested changes
let's add some more statistics for autohouse: list of the best-seller cars, best partners ( by amount of deals), the most expensive cars
as well general stats: amount of customers, average price of car in deals, the most successful autohouse( sort by the amount of received money from deals)

2023-02-23 14:30 UTC, shprexen requested changes

2023-02-24 09:20 UTC, jabajke commented on autohouse/services.py
> +            if customer_history.exists():
done

2023-02-28 17:25 UTC, shprexen approved these changes

2023-02-28 17:59 UTC, merged