Authentication
jabajke/autohouse pull request #2
Opened 2023-01-15 02:18 UTC by jabajke

2023-01-16 08:10 UTC, shprexen requested changes
merge previous branch to dev and then merge merge dev to your current feature branch to prevent merge conflicts

2023-01-16 08:10 UTC, shprexen commented on authentication/views.py
> +            serializer.save(user_id=user_id)
you don't need to decode your token for receiving user_id from payload, as you can get user object from `request.user`

2023-01-16 10:34 UTC, jabajke commented on authentication/views.py
> +            serializer.save(user_id=user_id)
@shprexen are u sure? so we dont have any user state using jwt, and i think that request.user would return anonymous

2023-01-16 11:06 UTC, shprexen commented on authentication/views.py
> +            serializer.save(user_id=user_id)
Do you get the token from query params?

2023-01-17 08:55 UTC, shprexen approved these changes

2023-01-20 18:29 UTC, merged