Debug toolbar
jabajke/autohouse pull request #6
Opened 2023-01-30 09:37 UTC by jabajke

2023-01-31 11:36 UTC, shprexen requested changes

2023-01-31 11:36 UTC, shprexen commented on core/settings.py
>  DEBUG = True
Specify DEBUG variable using env

2023-01-31 21:53 UTC, jabajke commented on core/settings.py
>  DEBUG = True
done

2023-02-02 16:24 UTC, shprexen approved these changes

2023-02-02 17:40 UTC, merged